#!/usr/bin/env bash
# This script contains the answers to the network type questions

echo "1. What type of network a computer in local is connected to?"
echo "The correct answer is: LAN"

echo "2. What type of network could connect an office in one building to another office in a building a few streets away?"
echo "The correct answer is: WAN"

echo "3. What network do you use when you browse www.google.com from your smartphone (not connected to the Wifi)?"
echo "The correct answer is: Internet"

